apps:
  - name: performance-service-api
    environment: production
    codebase: performance-service
    replicaCount: 1
    container:
      image:
        repository: osuakatsuki/performance-service
        tag: latest
      port: 80
      readinessProbe:
        httpGet:
          path: /_health
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
      env:
        - name: APP_COMPONENT
          value: api
      resources:
        limits:
          cpu: 300m
          memory: 250Mi
        requests:
          cpu: 150m
          memory: 100Mi
      imagePullSecrets:
        - name: osuakatsuki-registry-secret
    service:
      type: ClusterIP
      port: 80

  - name: performance-service-processor
    environment: production
    codebase: performance-service
    replicaCount: 1
    container:
      image:
        repository: osuakatsuki/performance-service
        tag: latest
      port: 80
      env:
        - name: APP_COMPONENT
          value: processor
      resources:
        limits:
          cpu: 300m
          memory: 250Mi
        requests:
          cpu: 150m
          memory: 100Mi
      imagePullSecrets:
        - name: osuakatsuki-registry-secret
    service:
      type: ClusterIP
      port: 80
