#!/bin/bash
#
# Generate a K8s Job manifest for PP recalculation
#
# Usage:
#   ./generate-job.sh [options]
#
# Examples:
#   # Full recalc (all modes, all variants)
#   ./generate-job.sh --name full-recalc
#
#   # Single beatmap test
#   ./generate-job.sh --name test-beatmap-75 --maps 75 --modes 0 --relax 0,1
#
#   # Only DT scores on std
#   ./generate-job.sh --name std-dt-only --modes 0 --relax 0,1,2 --mods 64
#
#   # Re-aggregate user totals only (skip score recalc)
#   ./generate-job.sh --name reaggregate --total-pp-only
#
# Then apply:
#   kubectl apply -f recalc-job-NAME.yaml
#

set -e

# Defaults
NAME=""
MODES="0,1,2,3"
RELAX_BITS="0,1,2"
TOTAL_PP_ONLY="0"
TOTAL_PP="1"
MAP_FILTER=""
MODS_FILTER=""
NEQ_MODS_FILTER=""
MAPPER_FILTER=""
OUTPUT_DIR="."

usage() {
    cat << EOF
Usage: $0 [options]

Required:
  --name NAME           Job name suffix (e.g., "full-recalc", "test-single")

Mode Selection:
  --modes MODES         Game modes, comma-separated (default: 0,1,2,3)
                        0=std, 1=taiko, 2=catch, 3=mania
  --relax BITS          Relax bits, comma-separated (default: 0,1,2)
                        0=vanilla, 1=relax, 2=autopilot

Phase Selection:
  --total-pp-only       Skip Phase 1 (score recalc), only aggregate user totals
  --no-total-pp         Skip Phase 2 (user aggregation), only recalc scores

Filters:
  --maps IDS            Filter to specific beatmap IDs (comma-separated)
  --mods BITMASK        Filter to scores WITH these mods
  --no-mods BITMASK     Filter to scores WITHOUT these mods
  --mapper NAME         Filter by mapper name (fuzzy match)

Output:
  --output-dir DIR      Output directory (default: current directory)

Common mod bitmasks:
  8=HD, 16=HR, 64=DT, 256=HT, 1024=FL
  72=HDDT, 80=HDHR, 88=HDHRDT

Examples:
  $0 --name full-recalc
  $0 --name test-beatmap --maps 75 --modes 0 --relax 0,1
  $0 --name std-dt-scores --modes 0 --mods 64
  $0 --name reaggregate-only --total-pp-only

EOF
    exit 1
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --name)
            NAME="$2"
            shift 2
            ;;
        --modes)
            MODES="$2"
            shift 2
            ;;
        --relax)
            RELAX_BITS="$2"
            shift 2
            ;;
        --total-pp-only)
            TOTAL_PP_ONLY="1"
            shift
            ;;
        --no-total-pp)
            TOTAL_PP="0"
            shift
            ;;
        --maps)
            MAP_FILTER="$2"
            shift 2
            ;;
        --mods)
            MODS_FILTER="$2"
            shift 2
            ;;
        --no-mods)
            NEQ_MODS_FILTER="$2"
            shift 2
            ;;
        --mapper)
            MAPPER_FILTER="$2"
            shift 2
            ;;
        --output-dir)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            echo "Unknown option: $1"
            usage
            ;;
    esac
done

# Validate required args
if [[ -z "$NAME" ]]; then
    echo "Error: --name is required"
    usage
fi

# Sanitize name for K8s (lowercase, alphanumeric and dashes only)
SAFE_NAME=$(echo "$NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')
JOB_NAME="performance-service-deploy-${SAFE_NAME}"
OUTPUT_FILE="${OUTPUT_DIR}/recalc-job-${SAFE_NAME}.yaml"

# Build optional env vars
OPTIONAL_ENVS=""

if [[ -n "$MAP_FILTER" ]]; then
    OPTIONAL_ENVS="${OPTIONAL_ENVS}
          - name: DEPLOY_MAP_FILTER
            value: \"${MAP_FILTER}\""
fi

if [[ -n "$MODS_FILTER" ]]; then
    OPTIONAL_ENVS="${OPTIONAL_ENVS}
          - name: DEPLOY_MODS_FILTER
            value: \"${MODS_FILTER}\""
fi

if [[ -n "$NEQ_MODS_FILTER" ]]; then
    OPTIONAL_ENVS="${OPTIONAL_ENVS}
          - name: DEPLOY_NEQ_MODS_FILTER
            value: \"${NEQ_MODS_FILTER}\""
fi

if [[ -n "$MAPPER_FILTER" ]]; then
    OPTIONAL_ENVS="${OPTIONAL_ENVS}
          - name: DEPLOY_MAPPER_FILTER
            value: \"${MAPPER_FILTER}\""
fi

# Generate the manifest
cat > "$OUTPUT_FILE" << EOF
# Generated by generate-job.sh
# Name: ${NAME}
# Command: $0 $@

apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
spec:
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: performance-service
        image: osuakatsuki/performance-service:latest
        imagePullPolicy: Always
        env:
          - name: KUBERNETES
            value: "true"
          - name: PULL_SECRETS_FROM_VAULT
            value: "1"
          - name: VAULT_ADDR
            valueFrom:
              secretKeyRef:
                name: vault
                key: address
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: vault
                key: token
          - name: APP_ENV
            value: production
          - name: APP_COMPONENT
            value: deploy
          - name: DEPLOY_MODES
            value: "${MODES}"
          - name: DEPLOY_RELAX_BITS
            value: "${RELAX_BITS}"
          - name: DEPLOY_TOTAL_PP_ONLY
            value: "${TOTAL_PP_ONLY}"
          - name: DEPLOY_TOTAL_PP
            value: "${TOTAL_PP}"${OPTIONAL_ENVS}
      restartPolicy: Never
      imagePullSecrets:
        - name: osuakatsuki-registry-secret
EOF

echo "Generated: ${OUTPUT_FILE}"
echo ""
echo "To apply:"
echo "  kubectl apply -f ${OUTPUT_FILE}"
echo ""
echo "To monitor:"
echo "  kubectl logs -f job/${JOB_NAME}"
echo ""
echo "To clean up:"
echo "  kubectl delete job ${JOB_NAME}"
